git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AbuseFilter.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AntiBot.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AntiSpoof.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ApiSandbox.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ArticleFeedback.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AssertEdit.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Babel.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CategoryTree.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CategoryTree.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CentralAuth.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CentralNotice.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CharInsert.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CheckUser.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Cite.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/cldr.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ClickTracking.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Collection.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ConfirmEdit.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DismissableSiteNotice.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/EditPageTracking.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/EducationProgram.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/EmailCapture.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/EventLogging.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ExpandTemplates.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/FeaturedFeeds.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/FlaggedRevs.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Gadgets.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/GlobalBlocking.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/GlobalUsage.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ImageMap.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/InputBox.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Interwiki.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/LocalisationUpdate.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MarkAsHelpful.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Math.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MobileFrontend.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MoodBar.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MWSearch.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Nuke.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/OAI.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/OpenSearchXml.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Oversight.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PagedTiffHandler.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PageTriage.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ParserFunctions.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PdfHandler.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Poem.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PoolCounter.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PostEdit.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Renameuser.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SecurePoll.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SimpleAntiSpam.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SiteMatrix.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SpamBlacklist.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SwiftCloudFiles.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SyntaxHighlight_GeSHi.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TimedMediaHandler.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/timeline.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TitleBlacklist.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TitleKey.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TorBlock.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TrustedXFF.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UploadBlacklist.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UserDailyContribs.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Vector.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikiEditor.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/wikihiero.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikiLove.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikimediaMessages.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikimediaShopLink.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ZeroRatedMobileAccess.git
